export const gamePageItems = [
    {
        idGame:1,
        title:'Hades',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/Hades.jpg',
        tags: ['Indie','Rogue-like','Singleplayer'],
        discount:50,
        full_price:20.99,
        link:'/hades',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/hades_home_page.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/Hades/hades_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/Hades/hades_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/Hades/hades_screenshot_3.jpg'],
        aboutTheGame:"Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles, including the fast-paced action of Bastion, the rich atmosphere and depth of Transistor, and the character-driven storytelling of Pyre.\n\nBATTLE OUT OF HELL\nAs the immortal Prince of the Underworld, you'll wield the powers and mythic weapons of Olympus to break free from the clutches of the god of the dead himself, while growing stronger and unraveling more of the story with each unique escape attempt.\n\nUNLEASH THE FURY OF OLYMPUS\nThe Olympians have your back! Meet Zeus, Athena, Poseidon, and many more, and choose from their dozens of powerful Boons that enhance your abilities. There are thousands of viable character builds to discover as you go.",
        reviews:"“Hades is a one-of-a-kind rogue-lite that does a brilliant job of marrying its fast-paced action with its persistent, progressing story through a vividly reimagined Greek mythological underworld.”\n9/10 - IGN\n\n“Hades is one of the best roguelites of all-time.”\n10/10 - TheSixthAxis\n\n“It's hard to imagine anyone other than Supergiant pulling off this Herculean feat with such style.\n”9/10 - Destructoid",
        systemReq:{
            win:{
                min:{
                    OS:'Windows 7 SP1',
                    Procesor:'Dual Core 2.4 GHz',
                    Mem:'4 GB RAM',
                    GrphCard:'1GB VRAM / DirectX 10+ support',
                    Storage:'15 GB available space',
                },
                rec:{
                    OS:'Windows 7 SP1',
                    Procesor:'Dual Core 3.0 GHz+',
                    Mem:'8 GB RAM',
                    GrphCard:'2GB VRAM / DirectX 10+ support',
                    Storage:'20 GB available space',
                }
            },
            mac:{
                min:{
                    OS:'10.13.6+',
                    Procesor:'Dual Core 2.4GHz',
                    Mem:'4 GB RAM',
                    GrphCard:'Intel HD 5000 (must support Metal API)',
                    Storage:'15 GB GB available space',
                },
                rec:{
                    OS:'macOS 10.14+',
                    Procesor:'Quad Core 3.0 GHz+',
                    Mem:'8 GB RAM',
                    GrphCard:'Intel UHD 630+ (must support Metal API)',
                    Storage:'20 GB available space',
                }
            },
        }
    },
    {
        idGame:2,
        title:'X4: Foundations',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/x4%20foundation.jpg',
        tags:['Si-Fi','Singleplayer'],
        discount:0,
        full_price:19.99,
        link:'/x4foundations',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/X4_Foundations_home_page.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/x4/x4_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/x4/x4_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/x4/x4_screenshot_3.jpg'],
        aboutTheGame:'',
        reviews:'',
        systemReq:{
            win:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
            mac:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
        }
    },
    {
        idGame:3,
        title:'Serious Sam:FE',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/serious%20sam%20FE.jpg',
        tags:['Indie','FPS','Singleplayer','Multiplayer','Co-op'],
        discount:25,
        full_price:14.99,
        link:'/serioussamthefe',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/Serious_Sam_home_page.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/SeriousSamFE/serious_sam_fe_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/SeriousSamFE/serious_sam_fe_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/SeriousSamFE/serious_sam_fe_screenshot_3.jpg'],
        aboutTheGame:'',
        reviews:'',
        systemReq:{
            win:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
            mac:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
        }
    },
    {
        idGame:4,
        title:'Need For Speed',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/Need%20for%20speed.jpg',
        tags:['Singleplayer','Sport','Racing'],
        discount:0,
        full_price:9.99,
        link:'/needforspeed',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/Need-For-Speed-home_page.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/NeedForSpeed/NeedForSpeed_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/NeedForSpeed/NeedForSpeed_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/NeedForSpeed/NeedForSpeed_screenshot_3.jpg'],
        aboutTheGame:'',
        reviews:'',
        systemReq:{
            win:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
            mac:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
        }
    },
    {
        idGame:5,
        title:'Call of Duty: MW2',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/COD%20MW2.jpg',
        tags:['FPS','Singleplayer','Multiplayer','Co-op'],
        discount:0,
        full_price:19.99,
        link:'/callofdutymw2',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/CoDmw2BP.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/CoDMW2/CoDMW2_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/CoDMW2/CoDMW2_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/CoDMW2/CoDMW2_screenshot_3.jpg'],
        aboutTheGame:'',
        reviews:'',
        systemReq:{
            win:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
            mac:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
        }
    },
    {
        idGame:6,
        title:'Bloons TD6',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/capsule_sm_120.jpg',
        tags:['Indie','Puzzle','Singleplayer','Co-op'],
        discount:0,
        full_price:8.19,
        link:'/bloonstd6',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/bloonsTD6BP.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/BloonsTD6/BloonsTD_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/BloonsTD6/BloonsTD_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/BloonsTD6/BloonsTD_screenshot_3.jpg'],
        aboutTheGame:'',
        reviews:'',
        systemReq:{
            win:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
            mac:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
        }
    },
    {
        idGame:7,
        title:'Bioshock Infinite',
        thumbnail:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/storePageThumbnails/bioshock%20inf.jpg',
        tags:['FPS','Singleplayer','Si-Fi'],
        discount:0,
        full_price:29.99,
        link:'/bioshockinfinite',
        bigPicture:'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/GDDbigPicture/bioshockInfiniteBp.jpg',
        screenshots:['https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/BioshockInfinite/Bioshock_Infinite_screenshot_1.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/BioshockInfinite/Bioshock_Infinite_screenshot_2.jpg',
        'https://raw.githubusercontent.com/DavorMeter/OGS_images_database/main/Screenshots/BioshockInfinite/Bioshock_Infinite_screenshot_3.jpg'],
        aboutTheGame:'',
        reviews:'',
        systemReq:{
            win:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
            mac:{
                min:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                },
                rec:{
                    OS:'',
                    Procesor:'',
                    Mem:'',
                    GrphCard:'',
                    Storage:'',
                }
            },
        }
    },
]